orjia/base/urls.py
from django.urls import path
from . import views as v
from django.conf import settings
from django.conf.urls.static import static

app_name = 'base'

urlpatterns = [
    path('', v.home, name='index'),
    path('login/', v.LoginView.as_view(), name='login'),
    path('logout/', v.LogoutView.as_view(), name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orjia/campanha/urls.py
from django.urls import path
from . import views as v

app_name = 'campanha'

urlpatterns = [
    # URLS CAMPANHA
    path('', v.CampanhaList.as_view(), name='campanha_list'),
    path('create/', v.CampanhaCreate.as_view(), name='campanha_create'),
    path('<int:pk>/', v.campanha_detail, name='campanha_detail'),
    path('update/<int:pk>/', v.CampanhaUpdate.as_view(), name='campanha_update'),

    # URLS COMPETIÇÃO
    path('competicao/create/', v.competicao_create, name='competicao_create'),
    path('competicao/update/<int:pk>/', v.CompeticaoUpdate.as_view(), name='competicao_update'),
    path('competicao/delete/<int:pk>', v.CompeticaoDelete.as_view(), name='competicao_delete'),
    path('competicao/<int:pk>/', v.competicao_detail, name='competicao_detail'),
]

orjia/orjia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('atletica/', include('atletica.urls')),
    path('modalidade/', include('modalidade.urls')),
    path('campanha/', include('campanha.urls')),
    path('partida/', include('partida.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orjia/partida/urls.py
from django.urls import path
from .views import CompeticaoResultadoUpdate
from . import views as v

app_name = "partida"

urlpatterns = [
    path("create/<int:pk>", v.partida_create, name="partida_create"),
    path("update/<int:pk>", v.PartidaUpdate.as_view(), name="partida_update"),
    path("delete/<int:pk>", v.PartidaDelete.as_view(), name="partida_delete"),
    path("<int:pk>/", v.partida_detail, name="partida_detail"),
    path(
        "gerenciar_resultados/<int:partida_pk>",
        CompeticaoResultadoUpdate.as_view(),
        name="gerenciar_resultados",
    ),
]

orjia/atletica/models.py
from django.db import models
from campanha.models import Campanha, Competicao, create_token
from django.utils.translation import gettext as _
from base.models import User
import os


def upload_photo(instance, filename):
    # /media/logos/<instance.id>-<token_aleatorio>.<extensao_do_arquivo>
    return f"logos/{instance.nome}-{create_token(4)}{os.path.splitext(filename)[-1]}"


class Atletica(models.Model):
    usuario = models.OneToOneField(User, related_name='usuario_atletica', on_delete=models.CASCADE)
    nome = models.CharField(verbose_name='Nome', max_length=150)
    email = models.CharField(verbose_name='Email', max_length=50, null=True, blank=True)
    curso = models.CharField(verbose_name='Curso', max_length=50, null=False, blank=False)
    instagram = models.CharField(verbose_name='Instagem da Atlética', max_length=40, null=True, blank=True)
    twitter = models.CharField(verbose_name='Twitter da Atlética', max_length=40, null=True, blank=True)
    logo = models.ImageField(upload_to=upload_photo, null=True)

    class Meta:
        ordering = ['nome']
        verbose_name = 'Atlética'
        verbose_name_plural = 'Atléticas'

    def __str__(self):
        return self.nome


class Atleta(models.Model):
    class Sex(models.TextChoices):
        MALE = 'M', _('Masculino')
        FEMALE = 'F', _('Feminino')

    nome = models.CharField(verbose_name='Nome do atleta', max_length=50, null=False, blank=False)
    matricula = models.PositiveIntegerField(verbose_name='Número da matricula', null=False, blank=False)
    chave = models.TextField(verbose_name='Chave de autenticação', max_length=39, null=False, blank=False)
    atletica = models.ForeignKey(Atletica, on_delete=models.CASCADE, null=True, blank=True)
    sex = models.CharField(verbose_name=_('Sexo'), max_length=1, choices=Sex.choices, default=Sex.MALE, null=True)
    status = models.BooleanField(default=True)

    class Meta:
        ordering = ['nome']
        verbose_name = 'Atleta'
        verbose_name_plural = 'Atletas'

    def __str__(self):
        return self.nome


class Equipe(models.Model):
    atletica = models.ForeignKey(Atletica, on_delete=models.CASCADE, null=True, blank=True)
    campanha = models.ForeignKey(Campanha, on_delete=models.CASCADE, null=True, blank=True)
    competicao = models.ForeignKey(Competicao, on_delete=models.CASCADE, null=True, blank=True)
    atleta = models.ManyToManyField(Atleta)
    sex = models.CharField('Sexo', max_length=1, null=True, blank=True)

    class Meta:
        ordering = ['competicao']
        verbose_name = 'Equipe'
        verbose_name_plural = 'Equipes'

    def __str__(self):
        nome = '{} - {}'.format(self.atletica.nome, self.competicao.modalidade.nome)
        return nome


class Score(models.Model):
    atletica = models.ForeignKey(Atletica, on_delete=models.PROTECT, null=True)
    campanha = models.ForeignKey(Campanha, on_delete=models.PROTECT)
    pontos = models.PositiveIntegerField(default=0, null=True)

    class Meta:
        ordering = ['pontos']
        verbose_name = 'Pontuação'
        verbose_name_plural = 'Pontuação'

orjia/partida/models.py
from django.db import models
from atletica.models import Equipe
from campanha.models import Competicao
from datetime import date

MD = (
    ('1', 'Um (1)'),
    ('3', 'Tres (3)'),
    ('5', 'Cinco (5)'),
)


class Partida(models.Model):
    class Etapa(models.TextChoices):
        PRE = 'P', ('Pre-liminar')
        OITAVAS = 'O', ('Oitavas')
        QUARTAS = 'Q', ('Quartas')
        DESEMPATE56 = 'D', ('Quartas-desempate | Quinto e Sexto')
        DESEMPATE78 = 'U', ('Quartas-desempate | Setimo e Oitavo')
        SEMI = 'S', ('Semi-final')
        TERCEIRO = 'T', ('Terceiro lugar')
        FINAL = 'F', ('Final')

    class Unidade(models.TextChoices):
        PONTOS = 'P', 'Pontos'
        SETS = 'S', 'Sets'
        GOLS = 'G', 'Gols'
        SEC = 'T', 'Segundos'
        MIN = 'M', 'Minutos'
        ROUNDS = 'R', 'Rodadas'
        GERAL = 'O', 'Geral'
        # RODADAS = 'O', ('Misto')

    competicao = models.ForeignKey(Competicao, on_delete=models.PROTECT, null=True, blank=True)
    numero = models.PositiveIntegerField('Sequencia do jogo', null=True, blank=True)
    data = models.DateField('Data da partida', default=date.today)
    local = models.CharField('Local do jogo', max_length=255, null=True, default='A definir')
    md = models.CharField('Melhor de:', max_length=1, choices=MD, default=1)
    equipes = models.ManyToManyField(Equipe, through='Competidor')
    unidade = models.CharField('Unidade', choices=Unidade.choices, max_length=1, default=Unidade.GERAL, null=True)
    etapa = models.CharField('Etapa', max_length=1, choices=Etapa.choices, default=Etapa.PRE, null=True)
    obs = models.TextField('Observações', blank=True, null=True)

    class Meta:
        ordering = ['numero']
        verbose_name = 'partida'
        verbose_name_plural = 'partidas'


class Competidor(models.Model):
    equipe = models.ForeignKey(Equipe, on_delete=models.PROTECT, null=True)
    partida = models.ForeignKey(Partida, on_delete=models.CASCADE, null=True)
    qualificador = models.CharField(max_length=1, null=True)
    resultado = models.PositiveIntegerField('Resultado da equipe', default=0, null=True, blank=True)


# class Pontuacao(models.Model):
#     class Unidade(models.TextChoices):
#         PONTOS = 'P', 'Pontos'
#         SETS = 'S', 'Sets'
#         GOLS = 'G', 'Gols'
#         SEC = 'T', 'Segundos'
#         MIN = 'M', 'Minutos'
#         ROUNDS = 'R', 'Rodadas'
#         GERAL = 'O', 'Geral'
#
#     competidor = models.ForeignKey(Competidor, on_delete=models.CASCADE)
#     unidade = models.CharField('Unidade', choices=Unidade.choices, max_length=1, default=Unidade.GERAL, null=True)
#     pontuacao = models.PositiveIntegerField('Pontuacao do jogo:', default=0, null=True, blank=True)
#     md = models.PositiveIntegerField(default=1)


class Ranking(models.Model):
    competicao = models.OneToOneField(Competicao, on_delete=models.CASCADE, null=True)
    equipe1 = models.ForeignKey(Equipe,
                                related_name='Primeiro_Lugar',
                                on_delete=models.PROTECT,
                                default='A definir',
                                null=True
                                )
    equipe2 = models.ForeignKey(Equipe,
                                related_name='Segundo_Lugar',
                                on_delete=models.PROTECT,
                                default='A definir',
                                null=True
                                )
    equipe3 = models.ForeignKey(Equipe,
                                related_name='Terceiro_Lugar',
                                on_delete=models.PROTECT,
                                default='A definir',
                                null=True
                                )
    equipe4 = models.ForeignKey(Equipe,
                                related_name='Quarto_Lugar',
                                on_delete=models.PROTECT,
                                default='A definir',
                                null=True
                                )
    equipe5 = models.ForeignKey(Equipe,
                                related_name='Quinto_Lugar',
                                on_delete=models.PROTECT,
                                default='A definir',
                                null=True
                                )
    equipe6 = models.ForeignKey(Equipe,
                                related_name='Sexto_Lugar',
                                on_delete=models.PROTECT,
                                default='A definir',
                                null=True
                                )
    equipe7 = models.ForeignKey(Equipe,
                                related_name='Setimo_Lugar',
                                on_delete=models.PROTECT,
                                default='A definir',
                                null=True
                                )
    equipe8 = models.ForeignKey(Equipe,
                                related_name='Oitavo_Lugar',
                                on_delete=models.PROTECT,
                                default='A definir',
                                null=True
                                )

    class Meta:
        verbose_name = 'ranking'
        verbose_name_plural = 'rankings'

orjia/templates/competicao/competicao_create.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Cadastro de competição{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <form method="post">
                <div class="card-header pb-0">
                    <div class="text-center">
                        <h4 class="mb-0 font-weight-bold">Informações da competição</h4>
                    </div>
                </div>

                <div class="card-body pt-0">
                    <div class="m-sm-4">
                        {% include 'forms/competicao_form.html' with form=form %}
                    </div>
                </div>
                <div class="text-center mt-3 mb-5">
                    <a href="{% url 'campanha:campanha_detail' campanha.pk %}" class="btn btn-lg btn-danger">Cancelar</a>
                    <button type="submit" class="btn btn-lg btn-success">Cadastrar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

orjia/templates/competicao/competicao_detail.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Detalhes da competição{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title text-dark"> Competição {{ competicao.modalidade }} - {{ competicao.get_sex_display }}</h2>
                <div class="card card-nav-tabs">
                    <div class="card-header card-header-primary">
                        <div class="nav-tabs-navigation">
                            <div class="nav-tabs-wrapper">
                                <ul class="nav nav-tabs" data-tabs="tabs">
                                    <li class="nav-item">
                                        <a class="nav-link active" href="#partidas" data-toggle="tab">Partidas</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#ranking" data-toggle="tab">Ranking - TOP 8</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!-- PARTIDAS -->
                    <div class="card-body ">
                        <div class="tab-content text-center">
                            <div class="tab-pane active" id="partidas">
                                {% if user.is_authenticated and user.is_staff %}
                                    <a class="btn btn-primary btn-round float-right mb-3"
                                        href="{% url 'partida:partida_create' competicao.pk %}">
                                        <span class="fa fa-plus"></span> Adicionar partida
                                    </a>
                                {% endif %}

                                {% if competidores %}
                                    <table id="tabelaPARTIDA" class="table table-striped table-responsive-sm">
                                        <thead>
                                        <tr>
                                            <th>Etapa</th>
                                            <th>Sequencia do jogo</th>
                                            <th>Atlética</th>
                                            <th></th>
                                            <th>X</th>
                                            <th></th>
                                            <th>Atlética</th>
                                            <th>Vencedor</th>
                                            <th>Ações</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for competidor in competidores %}
                                        <tr>
                                            <td>{{ competidor.0.partida.get_etapa_display }}</td>
                                            <td>{{ competidor.0.partida.numero }}</td>
                                            <td>{{ competidor.0.equipe.atletica.nome }}</td>
                                            <td>{{ competidor.0.resultado}}</td>
                                            <td>X</td>
                                            <td>{{ competidor.1.resultado}}</td>
                                            <td>{{ competidor.1.equipe.atletica.nome }}</td>
                                            <td>
                                                {% if competidor.0.resultado > competidor.1.resultado %}
                                                    {{ competidor.0.equipe.atletica.nome }}
                                                {% elif competidor.1.resultado > competidor.0.resultado %}
                                                    {{ competidor.1.equipe.atletica.nome }}
                                                {% else %}
                                                A DEFINIR
                                                {% endif %}
                                            </td>
                                            <td>
                                                {% if user.is_authenticated and user.is_staff %}
                                                <a href="{% url 'partida:partida_update' competidor.0.partida.pk %}">
                                                    <button type="button" rel="tooltip" data-placement="left"
                                                            title="Editar item"
                                                            class="btn btn-warning"><i class="bi bi-pencil-fill"></i>
                                                    </button>
                                                </a>
                                                <a href="{% url 'partida:gerenciar_resultados' competidor.0.partida.pk %}">
                                                    <button type="button" rel="tooltip" data-placement="left"
                                                            title="Gerenciar Resultado"
                                                            class="btn btn-primary"><i class="bi bi-card-list"></i>
                                                    </button>
                                                </a>
                                                {% endif %}
                                                <a href="{% url 'partida:partida_detail' competidor.0.partida.pk %}">
                                                    <button type="button" rel="tooltip" data-placement="left"
                                                            title="Visualizar item"
                                                            class="btn btn-info"><i class="bi bi-eye-fill"></i>
                                                    </button>
                                                </a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                {% else %}
                                    <br>
                                    <br>
                                    <p class="alert alert-warning">Sem partidas registradas.</p>
                                {% endif %}
                            </div>

                            <!-- RANKING -->
                            <div class="tab-pane" id="ranking">
                                {% if ranking %}
                                <table id="tabelaRANKING" class="table table-striped table-responsive-sm">
                                    <thead>
                                    <tr>
                                        <th>Colocação</th>
                                        <th>Equipes</th>
                                        <!--                        <th class="text-center">Ações</th>-->
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>1</td>
                                        <td>
                                            {% if ranking.0 %}
                                            {{ ranking.0 }}
                                            {% else %}
                                            A DEFINIR
                                            {% endif %}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>2</td>
                                        <td>
                                            {% if ranking.1 %}
                                            {{ ranking.1 }}
                                            {% else %}
                                            A DEFINIR
                                            {% endif %}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>3</td>
                                        <td>
                                            {% if ranking.2 %}
                                            {{ ranking.2 }}
                                            {% else %}
                                            A DEFINIR
                                            {% endif %}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>4</td>
                                        <td>
                                            {% if ranking.3 %}
                                            {{ ranking.3 }}
                                            {% else %}
                                            A DEFINIR
                                            {% endif %}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>5</td>
                                        <td>
                                            {% if ranking.4 %}
                                            {{ ranking.4 }}
                                            {% else %}
                                            A DEFINIR
                                            {% endif %}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>6</td>
                                        <td>
                                            {% if ranking.5 %}
                                            {{ ranking.5 }}
                                            {% else %}
                                            A DEFINIR
                                            {% endif %}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>7</td>
                                        <td>
                                            {% if ranking.6 %}
                                            {{ ranking.6 }}
                                            {% else %}
                                            A DEFINIR
                                            {% endif %}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>8</td>
                                        <td>
                                            {% if ranking.7 %}
                                            {{ ranking.7 }}
                                            {% else %}
                                            A DEFINIR
                                            {% endif %}
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>

                                {% else %}
                                <table id="tabelaRANKING" class="table table-striped table-responsive-sm">
                                    <thead>
                                    <tr>
                                        <th>Colocação</th>
                                        <th>Equipes</th>
                                        <!--                        <th class="text-center">Ações</th>-->
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>1</td>
                                        <td>A definir</td>
                                    </tr>
                                    <tr>
                                        <td>2</td>
                                        <td>A definir</td>
                                    </tr>
                                    <tr>
                                        <td>3</td>
                                        <td>A definir</td>
                                    </tr>
                                    <tr>
                                        <td>4</td>
                                        <td>A definir</td>
                                    </tr>
                                    <tr>
                                        <td>5</td>
                                        <td>A definir</td>
                                    </tr>
                                    <tr>
                                        <td>6</td>
                                        <td>A definir</td>
                                    </tr>
                                    <tr>
                                        <td>7</td>
                                        <td>A definir</td>
                                    </tr>
                                    <tr>
                                        <td>8</td>
                                        <td>A definir</td>
                                    </tr>
                                    </tbody>
                                </table>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

orjia/templates/competicao/competicao_detail_TxT.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Detalhes da competição{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title text-dark"> Competição {{ competicao.modalidade }} - {{ competicao.get_sex_display }}</h2>
                <div class="card-body ">
                    {% if ranking %}
                    <table id="tabelaRANKING" class="table table-striped table-responsive-sm">
                        <thead>
                        <tr>
                            <th>Colocação</th>
                            <th>Equipes</th>
                            <th>Resultado</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>1</td>
                            <td>
                                {% if ranking.0 %}
                                {{ ranking.0 }}
                                {% else %}
                                A DEFINIR
                                {% endif %}
                            </td>
                            <td>Resultado da equipe/competidor</td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>
                                {% if ranking.1 %}
                                {{ ranking.1 }}
                                {% else %}
                                A DEFINIR
                                {% endif %}
                            </td>
                            <td>Resultado da equipe/competidor</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>
                                {% if ranking.2 %}
                                {{ ranking.2 }}
                                {% else %}
                                A DEFINIR
                                {% endif %}
                            </td>
                            <td>Resultado da equipe/competidor</td>
                        </tr>
                        <tr>
                            <td>4</td>
                            <td>
                                {% if ranking.3 %}
                                {{ ranking.3 }}
                                {% else %}
                                A DEFINIR
                                {% endif %}
                            </td>
                            <td>Resultado da equipe/competidor</td>
                        </tr>
                        <tr>
                            <td>5</td>
                            <td>
                                {% if ranking.4 %}
                                {{ ranking.4 }}
                                {% else %}
                                A DEFINIR
                                {% endif %}
                            </td>
                            <td>Resultado da equipe/competidor</td>
                        </tr>
                        <tr>
                            <td>6</td>
                            <td>
                                {% if ranking.5 %}
                                {{ ranking.5 }}
                                {% else %}
                                A DEFINIR
                                {% endif %}
                            </td>
                            <td>Resultado da equipe/competidor</td>
                        </tr>
                        <tr>
                            <td>7</td>
                            <td>
                                {% if ranking.6 %}
                                {{ ranking.6 }}
                                {% else %}
                                A DEFINIR
                                {% endif %}
                            </td>
                            <td>Resultado da equipe/competidor</td>
                        </tr>
                        <tr>
                            <td>8</td>
                            <td>
                                {% if ranking.7 %}
                                {{ ranking.7 }}
                                {% else %}
                                A DEFINIR
                                {% endif %}
                            </td>
                            <td>Resultado da equipe/competidor</td>
                        </tr>
                        </tbody>
                    </table>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

orjia/templates/competicao/competicao_update.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Atualizar Competição{% endblock title %}

{% block content %}
<form method="POST">
    <div class="card">
        <div class="card-header pb-0">
            <div class="text-center">
                <h4 class="mb-0 font-weight-bold">Editar competição</h4>
            </div>
        </div>

        <div class="card-body pt-0">
            <div class="m-sm-4">
              {% include 'forms/competicao_form.html' with form=form %}
            </div>
        </div>
        <div class="text-center mt-3 mb-5">
            <a onclick="history.back()" class="btn btn-lg btn-danger">Cancelar</a>
            <button type="submit" class="btn btn-lg btn-success">Salvar</button>
        </div>
    </div>
</form>
{% endblock %}