orjia/base/urls.py
from django.urls import path
from . import views as v
from django.conf import settings
from django.conf.urls.static import static

app_name = 'base'

urlpatterns = [
    path('', v.home, name='index'),
    path('login/', v.LoginView.as_view(), name='login'),
    path('logout/', v.LogoutView.as_view(), name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orjia/campanha/urls.py
from django.urls import path
from . import views as v

app_name = 'campanha'

urlpatterns = [
    # URLS CAMPANHA
    path('', v.CampanhaList.as_view(), name='campanha_list'),
    path('create/', v.CampanhaCreate.as_view(), name='campanha_create'),
    path('<int:pk>/', v.campanha_detail, name='campanha_detail'),
    path('update/<int:pk>/', v.CampanhaUpdate.as_view(), name='campanha_update'),

    # URLS COMPETIÇÃO
    path('competicao/create/', v.competicao_create, name='competicao_create'),
    path('competicao/update/<int:pk>/', v.CompeticaoUpdate.as_view(), name='competicao_update'),
    path('competicao/delete/<int:pk>', v.CompeticaoDelete.as_view(), name='competicao_delete'),
    path('competicao/<int:pk>/', v.competicao_detail, name='competicao_detail'),
]

orjia/orjia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('atletica/', include('atletica.urls')),
    path('modalidade/', include('modalidade.urls')),
    path('campanha/', include('campanha.urls')),
    path('partida/', include('partida.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orjia/partida/urls.py
from django.urls import path
from .views import CompeticaoResultadoUpdate
from . import views as v

app_name = "partida"

urlpatterns = [
    path("create/<int:pk>", v.partida_create, name="partida_create"),
    path("update/<int:pk>", v.PartidaUpdate.as_view(), name="partida_update"),
    path("delete/<int:pk>", v.PartidaDelete.as_view(), name="partida_delete"),
    path("<int:pk>/", v.partida_detail, name="partida_detail"),
    path(
        "gerenciar_resultados/<int:partida_pk>",
        CompeticaoResultadoUpdate.as_view(),
        name="gerenciar_resultados",
    ),
]

orjia/atletica/models.py
from django.db import models
from campanha.models import Campanha, Competicao, create_token
from django.utils.translation import gettext as _
from base.models import User
import os


def upload_photo(instance, filename):
    # /media/logos/<instance.id>-<token_aleatorio>.<extensao_do_arquivo>
    return f"logos/{instance.nome}-{create_token(4)}{os.path.splitext(filename)[-1]}"


class Atletica(models.Model):
    usuario = models.OneToOneField(User, related_name='usuario_atletica', on_delete=models.CASCADE)
    nome = models.CharField(verbose_name='Nome', max_length=150)
    email = models.CharField(verbose_name='Email', max_length=50, null=True, blank=True)
    curso = models.CharField(verbose_name='Curso', max_length=50, null=False, blank=False)
    instagram = models.CharField(verbose_name='Instagem da Atlética', max_length=40, null=True, blank=True)
    twitter = models.CharField(verbose_name='Twitter da Atlética', max_length=40, null=True, blank=True)
    logo = models.ImageField(upload_to=upload_photo, null=True)

    class Meta:
        ordering = ['nome']
        verbose_name = 'Atlética'
        verbose_name_plural = 'Atléticas'

    def __str__(self):
        return self.nome


class Atleta(models.Model):
    class Sex(models.TextChoices):
        MALE = 'M', _('Masculino')
        FEMALE = 'F', _('Feminino')

    nome = models.CharField(verbose_name='Nome do atleta', max_length=50, null=False, blank=False)
    matricula = models.PositiveIntegerField(verbose_name='Número da matricula', null=False, blank=False)
    chave = models.TextField(verbose_name='Chave de autenticação', max_length=39, null=False, blank=False)
    atletica = models.ForeignKey(Atletica, on_delete=models.CASCADE, null=True, blank=True)
    sex = models.CharField(verbose_name=_('Sexo'), max_length=1, choices=Sex.choices, default=Sex.MALE, null=True)
    status = models.BooleanField(default=True)

    class Meta:
        ordering = ['nome']
        verbose_name = 'Atleta'
        verbose_name_plural = 'Atletas'

    def __str__(self):
        return self.nome


class Equipe(models.Model):
    atletica = models.ForeignKey(Atletica, on_delete=models.CASCADE, null=True, blank=True)
    campanha = models.ForeignKey(Campanha, on_delete=models.CASCADE, null=True, blank=True)
    competicao = models.ForeignKey(Competicao, on_delete=models.CASCADE, null=True, blank=True)
    atleta = models.ManyToManyField(Atleta)
    sex = models.CharField('Sexo', max_length=1, null=True, blank=True)

    class Meta:
        ordering = ['competicao']
        verbose_name = 'Equipe'
        verbose_name_plural = 'Equipes'

    def __str__(self):
        nome = '{} - {}'.format(self.atletica.nome, self.competicao.modalidade.nome)
        return nome


class Score(models.Model):
    atletica = models.ForeignKey(Atletica, on_delete=models.PROTECT, null=True)
    campanha = models.ForeignKey(Campanha, on_delete=models.PROTECT)
    pontos = models.PositiveIntegerField(default=0, null=True)

    class Meta:
        ordering = ['pontos']
        verbose_name = 'Pontuação'
        verbose_name_plural = 'Pontuação'

orjia/partida/models.py
from django.db import models
from atletica.models import Equipe
from campanha.models import Competicao
from datetime import date

MD = (
    ('1', 'Um (1)'),
    ('3', 'Tres (3)'),
    ('5', 'Cinco (5)'),
)


class Partida(models.Model):
    class Etapa(models.TextChoices):
        PRE = 'P', ('Pre-liminar')
        OITAVAS = 'O', ('Oitavas')
        QUARTAS = 'Q', ('Quartas')
        DESEMPATE56 = 'D', ('Quartas-desempate | Quinto e Sexto')
        DESEMPATE78 = 'U', ('Quartas-desempate | Setimo e Oitavo')
        SEMI = 'S', ('Semi-final')
        TERCEIRO = 'T', ('Terceiro lugar')
        FINAL = 'F', ('Final')

    class Unidade(models.TextChoices):
        PONTOS = 'P', 'Pontos'
        SETS = 'S', 'Sets'
        GOLS = 'G', 'Gols'
        SEC = 'T', 'Segundos'
        MIN = 'M', 'Minutos'
        ROUNDS = 'R', 'Rodadas'
        GERAL = 'O', 'Geral'
        # RODADAS = 'O', ('Misto')

    competicao = models.ForeignKey(Competicao, on_delete=models.PROTECT, null=True, blank=True)
    numero = models.PositiveIntegerField('Sequencia do jogo', null=True, blank=True)
    data = models.DateField('Data da partida', default=date.today)
    local = models.CharField('Local do jogo', max_length=255, null=True, default='A definir')
    md = models.CharField('Melhor de:', max_length=1, choices=MD, default=1)
    equipes = models.ManyToManyField(Equipe, through='Competidor')
    unidade = models.CharField('Unidade', choices=Unidade.choices, max_length=1, default=Unidade.GERAL, null=True)
    etapa = models.CharField('Etapa', max_length=1, choices=Etapa.choices, default=Etapa.PRE, null=True)
    obs = models.TextField('Observações', blank=True, null=True)

    class Meta:
        ordering = ['numero']
        verbose_name = 'partida'
        verbose_name_plural = 'partidas'


class Competidor(models.Model):
    equipe = models.ForeignKey(Equipe, on_delete=models.PROTECT, null=True)
    partida = models.ForeignKey(Partida, on_delete=models.CASCADE, null=True)
    qualificador = models.CharField(max_length=1, null=True)
    resultado = models.PositiveIntegerField('Resultado da equipe', default=0, null=True, blank=True)


# class Pontuacao(models.Model):
#     class Unidade(models.TextChoices):
#         PONTOS = 'P', 'Pontos'
#         SETS = 'S', 'Sets'
#         GOLS = 'G', 'Gols'
#         SEC = 'T', 'Segundos'
#         MIN = 'M', 'Minutos'
#         ROUNDS = 'R', 'Rodadas'
#         GERAL = 'O', 'Geral'
#
#     competidor = models.ForeignKey(Competidor, on_delete=models.CASCADE)
#     unidade = models.CharField('Unidade', choices=Unidade.choices, max_length=1, default=Unidade.GERAL, null=True)
#     pontuacao = models.PositiveIntegerField('Pontuacao do jogo:', default=0, null=True, blank=True)
#     md = models.PositiveIntegerField(default=1)


class Ranking(models.Model):
    competicao = models.OneToOneField(Competicao, on_delete=models.CASCADE, null=True)
    equipe1 = models.ForeignKey(Equipe,
                                related_name='Primeiro_Lugar',
                                on_delete=models.PROTECT,
                                default='A definir',
                                null=True
                                )
    equipe2 = models.ForeignKey(Equipe,
                                related_name='Segundo_Lugar',
                                on_delete=models.PROTECT,
                                default='A definir',
                                null=True
                                )
    equipe3 = models.ForeignKey(Equipe,
                                related_name='Terceiro_Lugar',
                                on_delete=models.PROTECT,
                                default='A definir',
                                null=True
                                )
    equipe4 = models.ForeignKey(Equipe,
                                related_name='Quarto_Lugar',
                                on_delete=models.PROTECT,
                                default='A definir',
                                null=True
                                )
    equipe5 = models.ForeignKey(Equipe,
                                related_name='Quinto_Lugar',
                                on_delete=models.PROTECT,
                                default='A definir',
                                null=True
                                )
    equipe6 = models.ForeignKey(Equipe,
                                related_name='Sexto_Lugar',
                                on_delete=models.PROTECT,
                                default='A definir',
                                null=True
                                )
    equipe7 = models.ForeignKey(Equipe,
                                related_name='Setimo_Lugar',
                                on_delete=models.PROTECT,
                                default='A definir',
                                null=True
                                )
    equipe8 = models.ForeignKey(Equipe,
                                related_name='Oitavo_Lugar',
                                on_delete=models.PROTECT,
                                default='A definir',
                                null=True
                                )

    class Meta:
        verbose_name = 'ranking'
        verbose_name_plural = 'rankings'

orjia/partida/views.py
from django.shortcuts import render, redirect, resolve_url
from django.contrib.auth.decorators import login_required
from django.views.generic import (
    CreateView,
    UpdateView,
    DeleteView)
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from .forms import (
    PartidaForm,
    RankingForm,
    PartidaUpdateForm,
    ResultadoForm,
    CompetidorResultadoUpdateForm,
    CompetidorResultadoUpdateFormSet,
)
from .models import Partida, Ranking, Competidor
from campanha.models import Competicao


@login_required
def partida_create(request, pk):
    competicao = Competicao.objects.get(pk=pk)
    partida_form = PartidaForm(request.POST or None, competicao=competicao)

    if request.method == "POST":
        if partida_form.is_valid():
            form = partida_form.save(commit=False)
            form.competicao = competicao
            form.save()
            partida_form.save_m2m()
            return redirect("campanha:competicao_detail", pk)

    return render(
        request,
        "partida/partida_create.html",
        {"competicao": competicao, "form": partida_form},
    )


class PartidaUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Partida
    form_class = PartidaUpdateForm
    template_name: str = "partida/partida_update.html"

    def get_context_data(self, *args, **kwargs):
        context = super(PartidaUpdate, self).get_context_data(*args, **kwargs)
        context["competicao"] = Competicao.objects.get(pk=self.object.competicao.pk)
        return context

    def get_success_url(self):
        return reverse_lazy(
            "campanha:competicao_detail", kwargs={"pk": self.object.competicao.pk}
        )


class PartidaDelete(LoginRequiredMixin, DeleteView, SuccessMessageMixin):
    model = Partida
    success_message = "Competicao removida com sucesso!"
    # success_url = reverse_lazy('campanha:campanha_detail')

    def get_success_url(self):
        return reverse_lazy(
            'campanha:competicao_detail', kwargs={"pk": self.object.competicao.pk}
        )


def partida_detail(request, pk):
    partida = Partida.objects.get(pk=pk)
    competidor_partida = Competidor.objects.filter(partida=partida)
    print(competidor_partida)
    context = {"partida": partida, "competidor": competidor_partida}
    return render(request, "partida/partida_detail.html", context)
    # pass


class CompeticaoResultadoUpdate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Competidor
    template_name = "competicao/gerenciar_resultado.html"
    form_class = CompetidorResultadoUpdateForm

    def get_context_data(self, **kwargs):
        context = super(CompeticaoResultadoUpdate, self).get_context_data(**kwargs)

        context["formset"] = CompetidorResultadoUpdateFormSet(
            queryset=Competidor.objects.filter(
                partida=self.kwargs["partida_pk"]
            ).prefetch_related("equipe")
        )
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        formset = CompetidorResultadoUpdateFormSet(request.POST)
        if formset.is_valid():
            return self.form_valid(formset)
        else:
            print(formset.errors)
            return self.form_invalid(formset)

    def get_success_url(self):
        competicao = Partida.objects.get(pk=self.kwargs["partida_pk"]).competicao
        return reverse_lazy("campanha:competicao_detail", kwargs={"pk": competicao.pk})

orjia/templates/partida/partida_create.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Registro da partida{% endblock title %}

{% block content %}
<div class="col-12">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <h2 class="card-title text-dark"> Competição {{ competicao.modalidade }} - {{ competicao.get_sex_display }}</h2>
                <form method="POST">
                    <div class="card">
                        <div class="card-header pb-0">
                            <div class="text-center">
                                <h4 class="mb-0 font-weight-bold">Informações da partida</h4>
                            </div>
                        </div>

                        <div class="card-body pt-0">
                            <div class="m-sm-4">
                                {% include 'forms/partida_form.html' with form=form %}
                            </div>
                        </div>
                        <div class="text-center mt-3 mb-5">
                            <a href="{% url 'campanha:competicao_detail' competicao.pk %}" class="btn btn-lg btn-danger">Cancelar</a>
                            <button type="submit" class="btn btn-lg btn-success">Cadastrar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block javascript %}
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function () {
        $('.js-example-basic-multiple').select2();
    });
</script>
{% endblock javascript %}

orjia/templates/partida/partida_detail.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Detalhes da competição{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-12">
        <h2 class="card-title text-dark"> Competição {{partida.competicao.modalidade}} - {{partida.competicao.get_sex_display}}</h2>
        <div class="card">
            <div class="card-body">
                <h4 class="card-title text-dark"> Partida - {{ partida.numero }} | {{partida.get_etapa_display}}
                    {% if user.is_authenticated and user.is_staff %}
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h2 class="text-center"></h2>
                        <span class="pull-right">
                                <a href="{% url 'partida:gerenciar_resultados' partida.pk %}">
                                <button type="button" class="btn btn-primary btn-round">
                                    <span class="fa fa-plus"></span> Gerenciar resultado
                                </button>
                                </a>
                            </span>
                    </div>
                    {% endif %}
                </h4>
                <div class="row mb-2 mt-2">
                    <div class="col-8">
                        {% include 'components/read_only_field.html' with value=partida.local label='Local' %}
                    </div>
                    <div class="col-4 col-md-2">
                        {% include 'components/read_only_field.html' with value=partida.data label='Data' %}
                    </div>
                </div>
                <div class="row mb-2 mt-2">
                    <div class="col-5 col-md-3">
                        {% include 'components/read_only_field.html' with value=competidor.0.equipe.atletica.nome label='Equipe A' %}
                    </div>
                    <!--                            <h2>X</h2>-->
                    <div class="col-5 col-md-3">
                        {% include 'components/read_only_field.html' with value=competidor.1.equipe.atletica.nome label='Equipe B' %}
                    </div>
                </div>
                <div class="col-12 mb-3">
                        {% include 'components/read_only_field.html' with value=partida.obs label='Observações' %}
                </div>
                {% if user.is_authenticated and user.is_staff %}
                <button type="button" rel="tooltip" data-placement="left" title="Apagar item" class="btn btn-danger"
                        data-toggle="modal" data-target="#modalPartida{{partida.pk}}">Excluir
                </button>
                <a href="{% url 'partida:partida_update' competidor.0.partida.pk %}"
                   class="btn btn-warning float-right">
                    Editar
                </a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalPartida{{partida.pk}}" tabindex="-1" role="dialog"
         aria-labelledby="TituloModalCentralizado" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="TituloModalCentralizado">Apagar Partida</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'partida:partida_delete' partida.pk %}" method="POST" novalidate>
                        {% csrf_token %}
                        <div class="row">
                            <div class="col">
                                Tem certeza que deseja apagar a partida?
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default btn-round" data-dismiss="modal">Cancelar
                            </button>
                            <button type="submit" class="btn btn-danger btn-round">Apagar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

orjia/templates/partida/partida_update.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Registro da partida{% endblock title %}

{% block content %}
<div class="col-12">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <h2 class="card-title text-dark"> Competição {{ competicao.modalidade.nome }} - {{ competicao.get_sex_display }}</h2>
                <form method="POST">
                    <div class="card">
                        <div class="card-header pb-0">
                            <div class="text-center">
                                <h4 class="mb-0 font-weight-bold">Informações da partida</h4>
                            </div>
                        </div>

                        <div class="card-body pt-0">
                            <div class="m-sm-4">
                                {% include 'forms/partida_form.html' with form=form %}
                            </div>
                        </div>
                        <div class="text-center mt-3 mb-5">
                            <a onclick="history.back()" class="btn btn-lg btn-danger">Cancelar</a>
                            <button type="submit" class="btn btn-lg btn-success">Salvar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block javascript %}
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function () {
        $('.js-example-basic-multiple').select2();
    });
</script>
{% endblock javascript %}