orjia/base/urls.py
from django.urls import path
from . import views as v
from django.conf import settings
from django.conf.urls.static import static

app_name = 'base'

urlpatterns = [
    path('', v.home, name='index'),
    path('login/', v.LoginView.as_view(), name='login'),
    path('logout/', v.LogoutView.as_view(), name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orjia/campanha/urls.py
from django.urls import path
from . import views as v

app_name = 'campanha'

urlpatterns = [
    # URLS CAMPANHA
    path('', v.CampanhaList.as_view(), name='campanha_list'),
    path('create/', v.CampanhaCreate.as_view(), name='campanha_create'),
    path('<int:pk>/', v.campanha_detail, name='campanha_detail'),
    path('update/<int:pk>/', v.CampanhaUpdate.as_view(), name='campanha_update'),

    # URLS COMPETIÇÃO
    path('competicao/create/', v.competicao_create, name='competicao_create'),
    path('competicao/update/<int:pk>/', v.CompeticaoUpdate.as_view(), name='competicao_update'),
    path('competicao/delete/<int:pk>', v.CompeticaoDelete.as_view(), name='competicao_delete'),
    path('competicao/<int:pk>/', v.competicao_detail, name='competicao_detail'),
]

orjia/orjia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('atletica/', include('atletica.urls')),
    path('modalidade/', include('modalidade.urls')),
    path('campanha/', include('campanha.urls')),
    path('partida/', include('partida.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orjia/campanha/models.py
import string
from distutils.command.upload import upload
from random import choice
from django.db import models
from modalidade.models import Modalidade
from datetime import date
import os

# Create your models here.
STATUS = (
    (1, 'ativo'),
    (0, 'inativo'),
)


def create_token(tam=8):
    token = ''
    choices = string.ascii_letters + string.digits
    for i in range(1, tam + 1):
        token += choice(choices)

        if i % 4 == 0 and i != tam:
            token += '.'

    return token.upper()


def upload_photo(instance, filename):
    # /media/logos/<instance.id>-<token_aleatorio>.<extensao_do_arquivo>
    return f"logos/{instance.pk}-{create_token(4)}{os.path.splitext(filename)[-1]}"


class Campanha(models.Model):
    # adm = models.ForeignKey(User, on_delete=models.PROTECT)
    nome = models.CharField(max_length=12, null=False, blank=False)
    data_inicio = models.DateField('Data de início', default=date.today)
    data_final = models.DateField('Data de término', default=date.today)
    ano = models.PositiveIntegerField('Ano do evento', null=False, blank=False)
    status = models.IntegerField(choices=STATUS, default=1)
    # logo = models.ImageField(upload_to='logos/', null=True)

    class Meta:
        ordering = ['ano']
        verbose_name = 'campanha'
        verbose_name_plural = 'campanhas'

    def __str__(self):
        return self.nome


class Competicao(models.Model):
    class Sex(models.TextChoices):
        MALE = 'M', ('Masculino')
        FEMALE = 'F', ('Feminino')
        MIX = 'O', ('Misto')

    campanha = models.ForeignKey(Campanha, on_delete=models.PROTECT, null=True, blank=True)
    modalidade = models.ForeignKey(Modalidade, on_delete=models.PROTECT)
    sex = models.CharField('Sexo', max_length=1, choices=Sex.choices, default=Sex.MALE, null=True)

    class Meta:
        ordering = ['campanha']
        verbose_name = 'competicao'
        verbose_name_plural = 'competicoes'

    def __str__(self):
        nome = "{} - {}".format(self.modalidade, self.sex)
        return nome

orjia/campanha/forms.py
from django import forms
from .models import Campanha, Competicao


class DateInput(forms.DateInput):
    input_type = "date"

    def __init__(self, **kwargs):
        super().__init__(format="%Y-%m-%d", attrs={"class": "form-control"})


class CampanhaForm(forms.ModelForm):
    class Meta:
        model = Campanha
        fields = ("nome", "data_inicio", "data_final", "ano")
        widgets = {
            "nome": forms.TextInput(
                attrs={
                    "class": "form-control form-control-lg",
                    "placeholder": "Nome da campanha",
                }
            ),
            "ano": forms.NumberInput(
                attrs={
                    "class": "form-control form-control-lg",
                    "placeholder": "Ano da campanha",
                }
            ),
            "data_inicio": DateInput(),
            "data_final": DateInput(),
        }


class CompeticaoForm(forms.ModelForm):
    class Meta:
        model = Competicao
        fields = ("modalidade", "sex", "campanha")
        widgets = {
            "modalidade": forms.Select(
                attrs={
                    "class": "form-control form-control-lg",
                    "placeholder": "Modalidade",
                }
            ),
            "sex": forms.Select(
                attrs={"class": "form-control form-control-lg text-center"}
            ),
            "campanha": forms.HiddenInput(),
        }


class CompeticaoUpdateForm(forms.ModelForm):
    class Meta:
        model = Competicao
        fields = ("modalidade", "sex")
        widgets = {
            "modalidade": forms.Select(
                attrs={
                    "class": "form-control form-control-lg",
                    "placeholder": "Modalidade",
                }
            ),
            "sex": forms.Select(
                attrs={"class": "form-control form-control-lg text-center"}
            ),
        }

orjia/campanha/views.py
from django.shortcuts import render, redirect, resolve_url
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from .models import Campanha, Competicao
from .forms import CampanhaForm, CompeticaoForm, CompeticaoUpdateForm
from django.views.generic import CreateView, DetailView, ListView, UpdateView, FormView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from partida.models import Partida, Ranking, Competidor
from partida.forms import RankingForm
from partida.services.partidas_service import make_ranking


class CampanhaCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = "campanha/campanha_create.html"
    model = Campanha
    form_class = CampanhaForm
    success_message = "Campanha %(nome)s cadastrada com sucesso"

    # success_url = reverse_lazy('atletica:atletica_detail')

    def get_success_url(self):
        return reverse_lazy("campanha:campanha_detail", kwargs={"pk": self.object.pk})


@login_required
def competicao_create(request):
    form = CompeticaoForm(request.POST or None)
    campanha = Campanha.objects.get(status=1)
    if form.is_valid():
        form = form.save(commit=False)
        form.campanha = campanha
        form.save()
        return redirect("campanha:campanha_detail", campanha.pk)
    return render(
        request,
        "competicao/competicao_create.html",
        {"form": form, "campanha": campanha},
    )


class CompeticaoDelete(LoginRequiredMixin, DeleteView, SuccessMessageMixin):
    model = Competicao
    success_message = "Competicao removida com sucesso!"
    # success_url = reverse_lazy('campanha:campanha_detail')

    def get_success_url(self):
        return reverse_lazy(
            'campanha:campanha_detail', kwargs={"pk": self.object.campanha.pk}
        )


class CompeticaoUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Competicao
    form_class = CompeticaoUpdateForm
    template_name: str = "competicao/competicao_update.html"
    success_message = "Competição atualizada com sucesso!"

    def get_success_url(self):
        return reverse_lazy(
            "campanha:campanha_detail", kwargs={"pk": self.object.campanha.id}
        )


class CampanhaDetail(SuccessMessageMixin, DetailView):
    model = Campanha
    template_name: str = "campanha/campanha_detail.html"


def campanha_detail(request, pk):
    template_name = "campanha/campanha_detail.html"
    campanha = Campanha.objects.get(pk=pk)
    competicao = Competicao.objects.filter(campanha=campanha).order_by('modalidade')
    context = {"campanha": campanha, "competicao": competicao}
    return render(request, template_name, context)


def competicao_detail(request, pk):
    competicao = Competicao.objects.get(pk=pk)
    if competicao.modalidade.tipo_confronto == '0':
        template_name = "competicao/competicao_detail.html"
    else:
        template_name = "competicao/competicao_detail_TxT.html"
    competidores = Partida.equipes.through.objects.filter(
        partida__competicao=competicao
    )
    # Monta uma lista L onde cada elemento é outra lista Lx, com 2 partida_competidores
    # Lx[i] é a equipe A da partida X e Lx[i + 1] é a equipe B da partida X
    partida_competidor = [
        [competidores[i], competidores[i + 1]] for i in range(0, len(competidores), 2)
    ]

    result_ranking = make_ranking(competicao)

    context = {
        "competicao": competicao,
        "competidores": partida_competidor,
        "ranking": result_ranking,
    }
    return render(request, template_name, context)


class CampanhaList(ListView):
    model = Campanha
    template = "campanha/campanha_list.html"


class CampanhaUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Campanha
    form_class = CampanhaForm
    template_name: str = "campanha/campanha_update.html"
    success_message = "Campanha %(nome)s atualizada com sucesso!"

    def get_success_url(self):
        return reverse_lazy("campanha:campanha_detail", kwargs={"pk": self.object.pk})


def ranking(request, pk):
    template_name = "ranking/ranking.html"
    competicao = Competicao.objects.get(pk=pk)
    # competidores = Partida.equipes.through.objects.filter(partida__competicao=competicao)
    partidas = Partida.objects.filter(
        competicao=competicao, etapa__in=["FINAL", "TERCEIRO"]
    )
    competidores = partidas.equipes.all()
    print(competidores)

    context = {"result": competidores}
    return render(request, template_name, context)

orjia/templates/campanha/campanha_create.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Cadastro de campanha{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <form method="post">
                <div class="card-header pb-0">
                    <div class="text-center">
                        <h4 class="mb-0 font-weight-bold">Informações da campanha</h4>
                    </div>
                </div>

                <div class="card-body pt-0">
                    <div class="m-sm-4">
                        {% include 'forms/campanha_form.html' with form=form %}
                    </div>
                </div>
                <div class="text-center mt-3 mb-5">
                    <a href="{% url 'campanha:campanha_list' %}" class="btn btn-lg btn-danger">Cancelar</a>
                    <button type="submit" class="btn btn-lg btn-success">Cadastrar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

orjia/templates/campanha/campanha_detail.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Detalhes da campanha{% endblock title %}

{% block content %}
{% if messages %}
<div class="row align-items-center py-4">
    <div class="col">
        {% include 'components/messages.html' %}
    </div>
</div>
{% endif %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title text-dark"> Campanha {{ campanha.nome }}
                    {% if user.is_authenticated and user.is_staff %}
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h2 class="text-center"></h2>
                        <span class="pull-right">
                            <a href="{% url 'campanha:competicao_create' %}">
                            <button type="button" class="btn btn-primary btn-round">
                                <span class="fa fa-plus"></span> Adicionar competição
                            </button>
                            </a>
                        </span>
                    </div>
                    {% endif %}
                </h2>
                <div class="row mb-2 mt-2">
                    <div class="col-12">
                        {% include 'components/read_only_field.html' with value=campanha.nome label='Nome' %}
                    </div>
                </div>
                <div class="row mb-2 mt-2">
                    <div class="col-12 col-md-6">
                        {% include 'components/read_only_field.html' with value=campanha.data_inicio label='Inicio' %}
                    </div>
                    <div class="col-12 col-md-6">
                        {% include 'components/read_only_field.html' with value=campanha.data_final label='Final' %}
                    </div>
                </div>
                {% if user.is_authenticated and user.is_staff %}
                <a href="{% url 'campanha:campanha_update' campanha.id %}" class="btn btn-warning float-right">
                    Editar
                </a>
                {% endif %}
                <br><br>
                <div class="col">
                    {% if competicao %}
                    {% for object in competicao %}
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body">
                                    <h2 class="card-title text-dark"> Competição {{ object.modalidade }}</h2>
                                    <div class="row mb-2 mt-2">
                                        <div class="col-12">
                                            {% include 'components/read_only_field.html' with value=object.get_sex_display label='Naipe' %}
                                        </div>
                                    </div>
                                    {% if user.is_authenticated and user.is_staff %}
                                    <button type="button" rel="tooltip" data-placement="left" title="Apagar item"
                                            class="btn btn-danger"
                                            data-toggle="modal" data-target="#modalCompeticao{{object.pk}}">Excluir
                                    </button>
                                    <a href="{% url 'campanha:competicao_update' object.pk %}"
                                       class="btn btn-warning">
                                        Editar
                                    </a>
                                    {% endif %}
                                    <a href="{% url 'campanha:competicao_detail' object.pk %}"
                                       class="btn btn-primary float-right">
                                        Detalhes
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>
                    <div class="modal fade" id="modalCompeticao{{object.pk}}" tabindex="-1" role="dialog"
                         aria-labelledby="TituloModalCentralizado" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="TituloModalCentralizado">Apagar Competicao</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <form action="{% url 'campanha:competicao_delete' object.pk %}" method="POST"
                                          novalidate>
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col">
                                                Tem certeza que deseja apagar a competicao {{object.nome}}?
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default btn-round"
                                                    data-dismiss="modal">Cancelar
                                            </button>
                                            <button type="submit" class="btn btn-danger btn-round">Apagar</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <div class="tab-content text-center">
                        <p class="alert alert-warning">Sem competições cadastradas.</p>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

orjia/templates/campanha/campanha_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Campanhas{% endblock title %}

{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h2 class="text-center"> Campanhas </h2>
    {% if user.is_authenticated and user.is_staff %}
    <a href="{% url 'campanha:campanha_create' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">Adicionar
        campanha</a>
    {% endif %}
</div>

{% if object_list %}
<div class="row mt-5">
    {% for campanha in object_list %}
    <a href="{% url 'campanha:campanha_detail' campanha.id %}">
        <div class="card" style="width: 18rem;">
            <img src="{% static 'img/orjia.png' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{campanha.nome}}</h5>
            </div>
        </div>
    </a>
    {% endfor %}
</div>
{% else %}
<div class="tab-content text-center">
    <p class="alert alert-warning">Sem campanhas cadastradas.</p>
</div>
{% endif %}
{% endblock %}

orjia/templates/campanha/campanha_update.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Atualizar Campanha{% endblock title %}

{% block content %}
<form method="POST">
    <div class="card">
        <div class="card-header pb-0">
            <div class="text-center">
                <h4 class="mb-0 font-weight-bold">Atualizar campanha {{ campanha.nome }}</h4>
            </div>
        </div>

        <div class="card-body pt-0">
            <div class="m-sm-4">
              {% include 'forms/campanha_form.html' with form=form %}
            </div>
        </div>
        <div class="text-center mt-3 mb-5">
            <a onclick="history.back()" class="btn btn-lg btn-danger">Cancelar</a>
            <button type="submit" class="btn btn-lg btn-success">Salvar</button>
        </div>
    </div>
</form>
{% endblock %}