orjia/atletica/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views as v

app_name = 'atletica'

urlpatterns = [
    path('', v.AtleticaList.as_view(), name='atletica_list'),
    path('add/', v.AtleticaCreate.as_view(), name='atletica_add'),
    path('<int:pk>', v.AtleticaDetail.as_view(), name='atletica_detail'),
    path('update/<int:pk>', v.AtleticaUpdate.as_view(), name='atletica_update'),
    path('delete/<int:pk>', v.AtleticaDelete.as_view(), name='atletica_delete'),

    # URLS ATLETAS
    path('atleta/list', v.atleta_list, name='atleta_list'),
    path('atleta/add/', v.atleta_add, name='atleta_add'),
    path('atleta/update/<int:pk>', v.AtletaUpdate.as_view(), name='atleta_update'),
    path('atleta/delete/<int:pk>', v.atleta_delete, name='atleta_delete'),

    # URLS EQUIPES
    path('equipe/', v.equipe_list, name='equipe_list'),
    path('equipe/add', v.equipe_create, name='equipe_create'),
    path('equipe/delete/<int:pk>', v.equipe_delete, name='equipe_delete'),
    path('equipe/update/<int:pk>', v.EquipeUpdate.as_view(), name='equipe_update'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orjia/base/urls.py
from django.urls import path
from . import views as v
from django.conf import settings
from django.conf.urls.static import static

app_name = 'base'

urlpatterns = [
    path('', v.home, name='index'),
    path('login/', v.LoginView.as_view(), name='login'),
    path('logout/', v.LogoutView.as_view(), name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orjia/campanha/urls.py
from django.urls import path
from . import views as v

app_name = 'campanha'

urlpatterns = [
    # URLS CAMPANHA
    path('', v.CampanhaList.as_view(), name='campanha_list'),
    path('create/', v.CampanhaCreate.as_view(), name='campanha_create'),
    path('<int:pk>/', v.campanha_detail, name='campanha_detail'),
    path('update/<int:pk>/', v.CampanhaUpdate.as_view(), name='campanha_update'),

    # URLS COMPETIÇÃO
    path('competicao/create/', v.competicao_create, name='competicao_create'),
    path('competicao/update/<int:pk>/', v.CompeticaoUpdate.as_view(), name='competicao_update'),
    path('competicao/delete/<int:pk>', v.CompeticaoDelete.as_view(), name='competicao_delete'),
    path('competicao/<int:pk>/', v.competicao_detail, name='competicao_detail'),
]

orjia/modalidade/urls.py
from django.urls import path
from . import views as v

app_name = 'modalidade'

urlpatterns = [
    path('', v.modalidade_list, name='modalidade_list'),
    path('add/', v.modalidade_add, name='modalidade_add'),
    path('edit/<int:pk>', v.ModalidadeUpdate.as_view(), name='modalidade_edit'),
    path('delete/<int:pk>', v.modalidade_delete, name='modalidade_delete'),
]

orjia/orjia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('atletica/', include('atletica.urls')),
    path('modalidade/', include('modalidade.urls')),
    path('campanha/', include('campanha.urls')),
    path('partida/', include('partida.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orjia/templates/components/field.html
{% if label %}
    <label class="form-label">{{ label }}
        {% if required %}
            <span style="color: red">*</span>
        {% endif %}
    </label>
{% endif %}

{{ field }}
{% if field.help_text %}<small class="form-text text-muted">{{ field.help_text }}</small>{% endif %}
{% if field.errors %}
    <div class="form-text text-danger font-weight-bold">
        {% if small %}<small style="font-size: 12px;">{% endif %}
        {% for error in field.errors %}
            {% if forloop.first %}
            {% else %}, {% endif %}
            {{ error|striptags }}
        {% endfor %}
        {% if small %}</small>{% endif %}
    </div>
{% endif %}

orjia/templates/components/footer.html
{% load static %}
<footer class="footer">
    <div class="container-fluid">
        <div class="row text-muted">
            <div class="col-6 text-left">
                <p class="mb-0">
                    <a href="index.html" class="text-muted"><strong>Universidade Federal do Acre</strong></a> &copy;
                </p>
            </div>
            <div class="col-6 text-right">
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <a class="text-muted" href="#">Support</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="text-muted" href="#">Help Center</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="text-muted" href="#">Privacy</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="text-muted" href="#">Terms</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

orjia/templates/components/form_messages.html
{% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger alert-outline alert-dismissible fade show" role="alert">
            <strong>{{error}}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
{% endif %}

orjia/templates/components/messages.html
{% for message in messages %}
    {% if message.tags == 'error' %}
        <div class="alert alert-danger alert-dismissible fade show">
            <strong>{{ message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    {% if message.tags == 'info' %}
        <div class="alert alert-info alert-dismissible fade show">
            <strong>{{ message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    {% if message.tags == 'success' %}
        <div class="alert alert-success alert-dismissible fade show">
            <strong>{{ message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    {% if message.tags == 'warning' %}
        <div class="alert alert-warning alert-dismissible fade show">
            <strong>{{ message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
{% endfor %}

orjia/templates/components/read_only_field.html
<div class="form-floating mb-3 fs-6">
  <label>
    {{ label }}
  </label>
  <input disabled class="form-control" value="{% if value %} {{ value }} {% endif %}"/>
</div>

orjia/templates/components/sidebar.html
{% load static %}
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-success sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'base:index' %}">
        <div class="sidebar-brand-icon">
            <!--            <i class="fas fa-laugh-wink"></i>-->
            <img src="{% static 'img/orjia.png' %}"
                 style="max-height:36%; max-width:36%;">
        </div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">
    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'base:index' %}">
            <i class="fa-solid fa-ranking-star"></i>
            <span>Ranking</span>
        </a>
        <a class="nav-link" href="{% url 'campanha:campanha_list' %}">
            <i class="fa-solid fa-otter"></i>
            <span>Campanhas</span>
        </a>
        <a class="nav-link" href="{% url 'atletica:atleta_list' %}">
            <i class="fa-solid fa-person-running"></i>
            <span>Atletas</span>
        </a>
        <a class="nav-link" href="{% url 'atletica:equipe_list' %}">
            <i class="fa-solid fa-people-group"></i>
            <span>Equipes</span>
        </a>
        <a class="nav-link" href="{% url 'modalidade:modalidade_list' %}">
            <i class="bi bi-table"></i>
            <span>Modalidades</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>
<!-- End of Sidebar -->

orjia/templates/components/sidebarCommunity.html
{% load static %}
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-success sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'base:index' %}">
        <div class="sidebar-brand-icon">
            <!--            <i class="fas fa-laugh-wink"></i>-->
            <img src="{% static 'img/orjia.png' %}"
                 style="max-height:36%; max-width:36%;">
        </div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">
    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'base:index' %}">
            <i class="fa-solid fa-ranking-star"></i>
            <span>Ranking</span>
        </a>
        <a class="nav-link" href="{% url 'campanha:campanha_list' %}">
            <i class="fa-solid fa-otter"></i>
            <span>Campanhas</span>
        </a>
        <a class="nav-link" href="{% url 'atletica:atletica_list' %}">
            <i class="fa-solid fa-basketball"></i>
            <span>Atleticas</span>
        </a>
        <a class="nav-link" href="{% url 'modalidade:modalidade_list' %}">
            <i class="bi bi-table"></i>
            <span>Modalidades</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>
<!-- End of Sidebar -->

orjia/templates/components/sidebarSTAFF.html
{% load static %}
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-success sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'base:index' %}">
        <div class="sidebar-brand-icon">
            <!--            <i class="fas fa-laugh-wink"></i>-->
            <img src="{% static 'img/orjia.png' %}" style="max-height:36%; max-width:36%;">
        </div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">
    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'base:index' %}">
            <i class="fa fa-clipboard"></i>
            <span>Dashboard</span>
        </a>
        <a class="nav-link" href="{% url 'base:campanha_create' %}">
            <i class="fa fa-users"></i>
            <span>Campanhas</span>
        </a>
        <a class="nav-link" href="{% url 'atletica:atletica_list' %}">
            <i class="fa fa-users"></i>
            <span>Atléticas</span>
        </a>
        <a class="nav-link" href="{% url 'modalidade:modalidade_list' %}">
            <i class="fa fa-users"></i>
            <span>Modalidades</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>
<!-- End of Sidebar -->

orjia/templates/components/sidebarStaff.html
{% load static %}
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-success sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'base:index' %}">
        <div class="sidebar-brand-icon">
            <!--            <i class="fas fa-laugh-wink"></i>-->
            <img src="{% static 'img/orjia.png' %}" style="max-height:36%; max-width:36%;">
        </div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">
    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'base:index' %}">
            <i class="fa-solid fa-ranking-star"></i>
            <span>Ranking</span>
        </a>
        <a class="nav-link" href="{% url 'campanha:campanha_list' %}">
            <i class="fa-solid fa-otter"></i>
            <span>Campanhas</span>
        </a>
        <a class="nav-link" href="{% url 'atletica:atletica_list' %}">
            <i class="fa-solid fa-basketball"></i>
            <span>Atléticas</span>
        </a>
        <a class="nav-link" href="{% url 'modalidade:modalidade_list' %}">
            <i class="bi bi-table"></i>
            <span>Modalidades</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>
<!-- End of Sidebar -->

orjia/templates/components/topbar.html
{% load static %}
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <!--        <div class="topbar-divider d-none d-sm-block"></div>-->
        {% if user.is_authenticated %}
        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user.email}}</span>
                <!--                <img class="img-profile rounded-circle"-->
                <!--                    src="{% static 'img/undraw_profile.svg' %}">-->
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                 aria-labelledby="userDropdown">
<!--                <a class="dropdown-item" href="#">-->
<!--                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>-->
<!--                    Perfil-->
<!--                </a>-->
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Sair
                </a>
            </div>
        </li>
    </ul>
    {% else %}
    <li class="nav-item mx-0 mx-lg-1">
        <a class="btn btn-primary" href="{% url 'base:login' %}">Login</a>
    </li>
    {% endif %}
</nav>
<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Logout</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Deseja mesmo sair da sessão atual?</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                <a class="btn btn-primary" href="{% url 'base:logout' %}">Confirmar</a>
            </div>
        </div>
    </div>
</div>

orjia/templates/components/topbarCOMUNIDADE.html
{% load static %}
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    <!-- Topbar Navbar -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#"><img src="{% static 'img/orjia.png' %}"
                                                  style="max-height:100%; max-width:100%;"></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Atleticas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Resultados</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Modalidades</a>
            </li>
        </ul>
    </div>
    <li class="nav-item mx-0 mx-lg-1">
        <a class="btn btn-primary" href="{% url 'base:login' %}">Login</a>
    </li>
</nav>

orjia/templates/components/topbarCommunity.html
{% load static %}
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    <!-- Topbar Navbar -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'base:index' %}"><img src="{% static 'img/orjia.png' %}"
                                                  style="max-height:100%; max-width:100%;"></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color:red;" href="{% url 'atletica:atletica_list' %}">Atleticas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color:red;" href="#">Resultados</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color:red;" href="{% url 'modalidade:modalidade_list' %}">Modalidades</a>
            </li>
        </ul>
    </div>
    <li class="nav-item mx-0 mx-lg-1">
        <a class="btn btn-primary" href="{% url 'base:login' %}">Login</a>
    </li>
</nav>